export const ApiRoutes = {
    auth: {
        switchOrganization: "/auth/switch-organization",
        email: {
            login: "/auth/email/login",
            register: "/auth/email/register",
            register_invitation: "/auth/email/register-invitation",
            invitation: "/auth/email/invitation",
            refresh_token: "/auth/email/refresh-token",
            admin_login_to_account: (account_uuid: string) => `/auth/email/${account_uuid}/admin-login`,
            forgot_password: "/auth/forgot-password",
            reset_password: "/auth/reset-password",
            verify_email: "/auth/verify-email",
            resend_verification_email: "/auth/resend-verification-email",
        },
    },
    users: {
        prefix: "/users",
        me: "/users/me",
        password: "/users/me/password",
    },
    google_maps: {
        timezone: "/google-maps/timezone",
    },
    organizations: {
        root: "/organizations",
        by_uuid: (organizationUuid: string) => `/organizations/${organizationUuid}`,
        members: (organizationUuid: string) => `/organizations/${organizationUuid}/members`,
        member: (organizationUuid: string, organizationMemberUuid: string) => `/organizations/${organizationUuid}/members/${organizationMemberUuid}`,
        resendMemberInvitation: (organizationUuid: string, organizationMemberUuid: string) =>
            `/organizations/${organizationUuid}/members/${organizationMemberUuid}/resend-invitation`,
        memberInvitationUrl: (organizationUuid: string, organizationMemberUuid: string) =>
            `/organizations/${organizationUuid}/members/${organizationMemberUuid}/invitation-url`,
        roles: (organizationUuid: string) => `/organizations/${organizationUuid}/roles`,
        role: (organizationUuid: string, organizationRoleUuid: string) => `/organizations/${organizationUuid}/roles/${organizationRoleUuid}`,
        rolePermissions: (organizationUuid: string, organizationRoleUuid: string) => `/organizations/${organizationUuid}/roles/${organizationRoleUuid}/permissions`,
        integrations: (organizationUuid: string) => `/organizations/${organizationUuid}/integrations`,
        integration: (organizationUuid: string, integrationUuid: string) => `/organizations/${organizationUuid}/integrations/${integrationUuid}`,
        integrationTest: (organizationUuid: string, integrationUuid: string) => `/organizations/${organizationUuid}/integrations/${integrationUuid}/test`,
        databaseIntegrations: (organizationUuid: string) => `/organizations/${organizationUuid}/database-integrations`,
        databaseIntegrationTestDraft: (organizationUuid: string) => `/organizations/${organizationUuid}/database-integrations/test`,
        databaseIntegration: (organizationUuid: string, integrationUuid: string) => `/organizations/${organizationUuid}/database-integrations/${integrationUuid}`,
        databaseIntegrationSync: (organizationUuid: string, integrationUuid: string) => `/organizations/${organizationUuid}/database-integrations/${integrationUuid}/sync`,
        databaseIntegrationTest: (organizationUuid: string, integrationUuid: string) => `/organizations/${organizationUuid}/database-integrations/${integrationUuid}/test`,
        openApiIntegrations: (organizationUuid: string) => `/organizations/${organizationUuid}/openapi-integrations`,
        openApiIntegrationParse: (organizationUuid: string) => `/organizations/${organizationUuid}/openapi-integrations/parse`,
        openApiIntegration: (organizationUuid: string, integrationUuid: string) => `/organizations/${organizationUuid}/openapi-integrations/${integrationUuid}`,
        openApiIntegrationRegenerate: (organizationUuid: string, integrationUuid: string) => `/organizations/${organizationUuid}/openapi-integrations/${integrationUuid}/regenerate`,
        openApiIntegrationTest: (organizationUuid: string, integrationUuid: string) => `/organizations/${organizationUuid}/openapi-integrations/${integrationUuid}/test`,
        integrationAppsToolkits: (organizationUuid: string) => `/organizations/${organizationUuid}/integrations/apps/toolkits`,
        integrationAppsToolkit: (organizationUuid: string, toolkitSlug: string) => `/organizations/${organizationUuid}/integrations/apps/toolkits/${toolkitSlug}`,
        integrationAppsToolkitTools: (organizationUuid: string, toolkitSlug: string) => `/organizations/${organizationUuid}/integrations/apps/toolkits/${toolkitSlug}/tools`,
        integrationAppsToolkitEnable: (organizationUuid: string, toolkitSlug: string) => `/organizations/${organizationUuid}/integrations/apps/toolkits/${toolkitSlug}/enable`,
        integrationAppsToolkitDisable: (organizationUuid: string, toolkitSlug: string) => `/organizations/${organizationUuid}/integrations/apps/toolkits/${toolkitSlug}/disable`,
        integrationAppsConnect: (organizationUuid: string) => `/organizations/${organizationUuid}/integrations/apps/connect`,
        integrationAppsCallback: (organizationUuid: string) => `/organizations/${organizationUuid}/integrations/apps/callback`,
        integrationAppsAccounts: (organizationUuid: string) => `/organizations/${organizationUuid}/integrations/apps/accounts`,
        integrationAppsAccount: (organizationUuid: string, connectedAccountId: string) => `/organizations/${organizationUuid}/integrations/apps/accounts/${connectedAccountId}`,
        integrationAppsReconnect: (organizationUuid: string, connectedAccountId: string) => `/organizations/${organizationUuid}/integrations/apps/accounts/${connectedAccountId}/reconnect`,
        integrationAppsTools: (organizationUuid: string) => `/organizations/${organizationUuid}/integrations/apps/tools`,
        integrationAppsToolPermission: (organizationUuid: string, toolSlug: string) => `/organizations/${organizationUuid}/integrations/apps/tools/${toolSlug}`,
        integrationAppsTriggers: (organizationUuid: string) => `/organizations/${organizationUuid}/integrations/apps/triggers`,
        integrationAppsTrigger: (organizationUuid: string, triggerUuid: string) => `/organizations/${organizationUuid}/integrations/apps/triggers/${triggerUuid}`,
        mcpIntegrations: (organizationUuid: string) => `/organizations/${organizationUuid}/integrations/mcp`,
        mcpIntegrationTestConnection: (organizationUuid: string) => `/organizations/${organizationUuid}/integrations/mcp/test-connection`,
        mcpIntegration: (organizationUuid: string, integrationUuid: string) => `/organizations/${organizationUuid}/integrations/mcp/${integrationUuid}`,
        mcpIntegrationSyncTools: (organizationUuid: string, integrationUuid: string) => `/organizations/${organizationUuid}/integrations/mcp/${integrationUuid}/sync-tools`,
        mcpIntegrationTest: (organizationUuid: string, integrationUuid: string) => `/organizations/${organizationUuid}/integrations/mcp/${integrationUuid}/test`,
        integrationActions: (organizationUuid: string, integrationUuid: string) => `/organizations/${organizationUuid}/integrations/${integrationUuid}/actions`,
        integrationAction: (organizationUuid: string, integrationUuid: string, actionUuid: string) => `/organizations/${organizationUuid}/integrations/${integrationUuid}/actions/${actionUuid}`,
        conversations: (organizationUuid: string) => `/organizations/${organizationUuid}/conversations`,
        conversation: (organizationUuid: string, conversationUuid: string) => `/organizations/${organizationUuid}/conversations/${conversationUuid}`,
        conversationMessages: (organizationUuid: string, conversationUuid: string) => `/organizations/${organizationUuid}/conversations/${conversationUuid}/messages`,
        conversationMessage: (organizationUuid: string, conversationUuid: string, messageUuid: string) => `/organizations/${organizationUuid}/conversations/${conversationUuid}/messages/${messageUuid}`,
        conversationAgentTools: (organizationUuid: string) => `/organizations/${organizationUuid}/conversations/agent-tools`,
        conversationPersonalization: (organizationUuid: string) => `/organizations/${organizationUuid}/conversation-personalization`,
        executions: (organizationUuid: string) => `/organizations/${organizationUuid}/executions`,
        execution: (organizationUuid: string, executionUuid: string) => `/organizations/${organizationUuid}/executions/${executionUuid}`,
        executionApprove: (organizationUuid: string, executionUuid: string) => `/organizations/${organizationUuid}/executions/${executionUuid}/approve`,
        executionReject: (organizationUuid: string, executionUuid: string) => `/organizations/${organizationUuid}/executions/${executionUuid}/reject`,
    },
    permissions: {
        root: "/permissions",
    },
    admin: {
        integrationAppsToolkits: "/admin/integrations/apps/toolkits",
        integrationAppsToolkit: (toolkitSlug: string) => `/admin/integrations/apps/toolkits/${toolkitSlug}`,
        integrationAppsToolkitTools: (toolkitSlug: string) => `/admin/integrations/apps/toolkits/${toolkitSlug}/tools`,
        integrationAppsToolkitTool: (toolkitSlug: string, toolSlug: string) => `/admin/integrations/apps/toolkits/${toolkitSlug}/tools/${toolSlug}`,
        integrationAppsToolkitRefresh: (toolkitSlug: string) => `/admin/integrations/apps/toolkits/${toolkitSlug}/refresh`,
        integrationAppsToolkitSyncTools: (toolkitSlug: string) => `/admin/integrations/apps/toolkits/${toolkitSlug}/sync-tools`,
        integrationAppsToolkitStats: (toolkitSlug: string) => `/admin/integrations/apps/toolkits/${toolkitSlug}/stats`,
        integrationAppsOverviewStats: "/admin/integrations/apps/stats",
        integrationAppsSync: "/admin/integrations/apps/sync",
        integrationAppsSyncRun: (syncRunUuid: string) => `/admin/integrations/apps/sync/${syncRunUuid}`,
    },
    aiProviders: (orgUuid: string) => `/organizations/${orgUuid}/ai-providers`,
    aiProvider: (orgUuid: string, providerUuid: string) => `/organizations/${orgUuid}/ai-providers/${providerUuid}`,
    usage: (orgUuid: string) => `/organizations/${orgUuid}/executions/usage`,
    usageRecords: (orgUuid: string) => `/organizations/${orgUuid}/executions/usage/records`,
    auditLogs: (orgUuid: string) => `/organizations/${orgUuid}/audit-logs`,
    documents: (orgUuid: string) => `/organizations/${orgUuid}/documents`,
    documentWidgetContent: (orgUuid: string, documentUuid: string) =>
        `/organizations/${orgUuid}/documents/${documentUuid}/widget-content`,
}
