import { useOrganizationStore } from '@/stores/organization';
import { useGetExecutions } from '@/features/executions/hooks/use-executions';
import { useNavigate } from 'react-router-dom';
import { Routes } from '@/routes/routes';
import { BarChart2, File, FileSpreadsheet, FileText } from 'lucide-react';

const outputTypeIcon = (outputType: string) => {
  switch (outputType) {
    case 'FILE_PDF':
      return <FileText className="h-5 w-5 text-red-400" />;
    case 'FILE_EXCEL':
      return <FileSpreadsheet className="h-5 w-5 text-green-400" />;
    case 'FILE_WORD':
      return <File className="h-5 w-5 text-blue-400" />;
    case 'CHART':
      return <BarChart2 className="h-5 w-5 text-accent" />;
    default:
      return <File className="h-5 w-5 text-muted" />;
  }
};

export default function FilesPage() {
  const orgUuid = useOrganizationStore((s) => s.current_organization?.uuid);
  const { data: executions = [], isLoading } = useGetExecutions(orgUuid);
  const navigate = useNavigate();

  const fileExecutions = executions.filter(
    (e) => e.output?.outputType && e.output.outputType !== 'TEXT',
  );

  return (
    <div className="mx-auto flex max-w-5xl flex-col gap-6">
      <header>
        <h1 className="text-lg font-semibold tracking-tight text-foreground">Files</h1>
        <p className="mt-0.5 text-sm text-muted">
          Documents, charts, and widgets generated by your agents.
        </p>
      </header>

      {isLoading && <p className="text-sm text-muted">Loading...</p>}

      {!isLoading && fileExecutions.length === 0 && (
        <p className="text-sm text-muted">No files generated yet.</p>
      )}

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {fileExecutions.map((execution) => (
          <div
            key={execution.uuid}
            className="flex flex-col gap-3 rounded-xl border border-border bg-surface p-4 hover:border-accent/40 transition-colors cursor-pointer"
            onClick={() => navigate(Routes.dashboard.execution(execution.uuid))}
          >
            <div className="flex items-start justify-between gap-2">
              <div className="flex items-center gap-2">
                {outputTypeIcon(execution.output!.outputType)}
                <span className="text-xs font-medium text-muted uppercase tracking-wide">
                  {execution.output!.outputType.replace('FILE_', '')}
                </span>
              </div>
              <span
                className={`rounded-full px-2 py-0.5 text-[10px] font-medium ${
                  execution.status === 'COMPLETED'
                    ? 'bg-green-500/10 text-green-400'
                    : execution.status === 'FAILED'
                    ? 'bg-red-500/10 text-red-400'
                    : 'bg-surface-secondary text-muted'
                }`}
              >
                {execution.status}
              </span>
            </div>

            {execution.output!.files.length > 0 && (
              <div className="flex flex-col gap-1.5">
                {execution.output!.files.map((fileUrl, i) => {
                  const filename = fileUrl.split('/').pop() ?? `file-${i + 1}`;
                  return (
                    <a
                      key={fileUrl}
                      href={fileUrl}
                      download={filename}
                      onClick={(e) => e.stopPropagation()}
                      className="truncate text-xs text-accent hover:underline"
                    >
                      {filename}
                    </a>
                  );
                })}
              </div>
            )}

            <p className="text-xs text-muted">{new Date(execution.created_at).toLocaleString()}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
